name: motor_unit_toolbox
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - scikit-learn
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - pytest
  - pytest-cov
  - hypothesis
  - pip
  - pip:
      - networkx
      - easydict
